services:
    alco_stop.admin.party_time:
        class: AlcoStop\Bundle\PartyTimeBundle\Admin\PartyTimeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Party activities" }
        arguments:
            - ~
            - AlcoStop\Bundle\PartyTimeBundle\Entity\DrinkActivity
            - ~
    alco_stop.service.party_time:
        class: AlcoStop\Bundle\PartyTimeBundle\Service\PartyTimeService
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
