services:
    alco_stop.admin.drink:
        class: AlcoStop\Bundle\DrinkBundle\Admin\DrinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Drink" }
        arguments:
            - ~
            - AlcoStop\Bundle\DrinkBundle\Entity\Drink
            - ~
